/* eslint-disable @typescript-eslint/ban-types */
// Auto-generated by scripts/export_schema.py; do not edit manually.

export interface Edge {
  id?: string | null;
  from_id: string;
  to_id: string;
  active?: boolean | null;
  commentaire?: string | null;
  geometry?: number[][] | null;
  branch_id: string;
  diameter_mm?: number | null;
  length_m?: number | null;
  material?: string | null;
  sdr?: string | null;
  site_id?: string | null;
  extras?: Record<string, unknown> | null;
  [key: string]: unknown;
}

export interface Node {
  id: string;
  name?: string | null;
  type?: string | null;
  branch_id?: string | null;
  site_id?: string | null;
  diameter_mm?: number | null;
  material?: string | null;
  commentaire?: string | null;
  collector_well_ids?: string[] | null;
  well_collector_id?: string | null;
  well_pos_index?: number | null;
  pm_collector_id?: string | null;
  pm_collector_edge_id?: string | null;
  pm_pos_index?: number | null;
  pm_offset_m?: number | null;
  gps_locked?: boolean | null;
  gps_lat?: number | null;
  gps_lon?: number | null;
  x?: number | null;
  y?: number | null;
  x_ui?: number | null;
  y_ui?: number | null;
  extras?: Record<string, unknown> | null;
  [key: string]: unknown;
}

export interface Graph {
  version?: string | null;
  site_id?: string | null;
  generated_at?: string | null;
  style_meta?: Record<string, unknown> | null;
  crs?: {
    code?: string | null;
    projected_for_lengths?: string | null;
    [key: string]: unknown;
  } | null;
  branches?: Array<{
    id: string;
    name?: string | null;
    parent_id?: string | null;
    is_trunk?: boolean | null;
    [key: string]: unknown;
  }> | null;
  nodes: Node[];
  edges: Edge[];
}

export type GraphPayload = Graph;
